### ISSUE TITLE
Delete note

### ISSUE THREAD

**Issue by maiph** [fabiospampinato/noty#4] opened 2018-10-02 21:23 UTC
Add a shortcut to delete a note. Maybe `ctrl+f4`

**Comment by fabiospampinato** [comment] 2018-10-02 21:33
What OS are you on?

**Comment by maiph** [comment] 2018-10-02 21:46
Windows 10

**Comment by fabiospampinato** [comment] 2018-10-02 22:01
There's actually a menubar where the Delete action is available, for some reason when I tested Noty under Windows and Ubuntu I wasn't enable to show it. It's supposed to appear when the `alt` key is pressed, can you reproduce?

**Comment by maiph** [comment] 2018-10-02 22:03
Nothing happens when I press `alt`

**Comment by fabiospampinato** [comment] 2018-10-02 22:10
I would consider that a bug 🤔 

I'll add a shortcut for it when I can 👍

**Comment by maiph** [comment] 2018-10-02 22:14
I think when you `frame: false` in the window options it doesn't render the menu on Windows.

I don't know if there is any way to render. Maybe you could create your own menu and add it in the html

**Comment by fabiospampinato** [comment] 2018-10-02 22:19
I'll investigate that. Adding a custom menu seems too much of a burden.

Maybe I shouldn't use a frameless window on Windows/Linux, but then the app would not look nice.

**Comment by maiph** [comment] 2018-10-02 22:24
Yeah, adding shortcuts would be  a better option. 

Also, have you considered adding one another circle like the red one on the top to make the window always on top? And when i alt tab out of the app, that red circle turn white or transparent.

**Comment by fabiospampinato** [comment] 2018-10-02 22:31
That red circle is supposed to mimic the close button in macOS. It looks totally out of place under Windows/Linux. It turns white because that's what the native button in macOS does. Maybe I should replace it with something entirely custom, but I don't have time for this atm.

There's actually an option for toggling "Float on Top, but that's in the menu.

**Comment by fabiospampinato** [comment] 2018-10-03 18:44
I'm uploading v2.1.0 right now, you can now delete notes with a `ctrl+alt+backspace`. 

Maybe the app will update itself the next time you close it, I've never actually tested this. If it doesn't just download the updated version.

**Closed as completed by fabiospampinato** 2018-10-03 18:44 UTC
Labels: enhancement

**Comment by fabiospampinato** [comment] 2018-10-03 18:53
> Maybe the app will update itself the next time you close it, I've never actually tested this.

It worked for me, awesome. You should get a notification when a new version has been downloaded.

**Comment by PAC-Bayesian** [comment] 2019-08-02 23:22
Hi! I am using Noty v2.2.0 on Window 10 Pro. It seems the shortcut of deletion does not work as I have tried all the combinations involved <kbd>Ctrl</kbd>, <kbd>Alt</kbd> and <kbd>Backspace</kbd>. But all the other shortcuts are perfect!

**Comment by fabiospampinato** [comment] 2019-08-03 13:18
@PAC-Bayesian in the near-ish future Noty is going to get deprecated in favor of [Notable](https://github.com/notable/notable), so I don't think it's worth spending any more time maintaining Noty.
